name: Build LibCore AAR
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag to build'
        required: true
        default: 'main'

jobs:
  libcore:
    name: Build & Publish libcore.aar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository at ${{ github.event.inputs.ref }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Compute build status hashes
        run: |
          find buildScript libcore/*.sh | xargs cat | sha1sum > golang_status
          git ls-files libcore | xargs cat | sha1sum > libcore_status

      - name: Install Go
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build libcore
        if: steps.cache.outputs.cache-hit != 'true'
        run: ./run lib core

      - name: Upload libcore.aar artifact
        uses: actions/upload-artifact@v4
        with:
          name: libcore.aar
          path: app/libs/libcore.aar
